// frontend/src/pages/Host.tsx
import React, { useEffect, useRef, useState } from "react";
import { WebSocketMessage, Params } from "../generated/messages";
import { socket } from "../socket";
import MovingCircle from "../components/MovingCircle";
import "./Host.css";

const THROTTLE_MS = 200;

const Host: React.FC = () => {
    const [size, setSize] = useState(40);
    const [speed, setSpeed] = useState(200);
    const [color, setColor] = useState("#00ff00");
    const [isUpdated, setIsUpdated] = useState(false);
    const [isPlaying, setIsPlaying] = useState(true);

    const [sessionUrl, setSessionUrl] = useState<string | null>(null);
    const [sid, setSid] = useState<string | null>(null);

    // resetToken – powoduje start od lewej po zmianie (używany TYLKO przy joinie)
    const [resetToken, setResetToken] = useState(0);
    const [bounceCount, setBounceCount] = useState(0);

    // Status klienta
    const [clientConnected, setClientConnected] = useState(false);

    useEffect(() => {
        if (socket) socket.binaryType = "arraybuffer";
    }, []);

    const toUint8Array = async (data: unknown): Promise<Uint8Array> => {
        if (data instanceof ArrayBuffer) return new Uint8Array(data);
        if (data instanceof Blob) return new Uint8Array(await data.arrayBuffer());
        if (typeof data === "string") return new TextEncoder().encode(data);
        // @ts-ignore
        if (data?.byteLength && data?.buffer) return new Uint8Array(data);
        throw new Error("[Host] Nieznany typ danych z WebSocket");
    };

    useEffect(() => {
        const onMessage = async (ev: MessageEvent) => {
            try {
                const buffer = await toUint8Array(ev.data);
                const msg = WebSocketMessage.decode(buffer);

                if (msg.createSessionResponse) {
                    const { accepted, sessionUrl } = msg.createSessionResponse;
                    if (accepted && sessionUrl) {
                        setSessionUrl(sessionUrl);
                        setClientConnected(false); // nowa sesja – reset statusu klienta
                        try {
                            const u = new URL(sessionUrl);
                            const s = u.searchParams.get("sid");
                            if (s) setSid(s);
                        } catch {
                            const parts = String(sessionUrl).split("sid=");
                            if (parts[1]) setSid(parts[1].split("&")[0]);
                        }
                    }
                } else if (msg.joinSessionResponse) {
                    if (msg.joinSessionResponse.accepted) {
                        setClientConnected(true);
                        setResetToken(t => t + 1);
                        setBounceCount(0);
                    }
                } else if (msg.params) {
                    // echo/odbicia – bez resetu
                    // console.log("[Host] Echo Params:", msg.params);
                } else if (msg.play) {
                    setIsPlaying(true);
                } else if (msg.stop) {
                    setIsPlaying(false);
                }
            } catch (e) {
                console.error("[Host] Decode error:", e);
            }
        };

        socket.addEventListener("message", onMessage);
        return () => {
            socket.removeEventListener("message", onMessage);
        };
    }, []);

    // Wspólna wysyłka parametrów (bez resetu!)
    const sendParams = () => {
        if (!socket || socket.readyState !== WebSocket.OPEN) {
            console.warn("WebSocket nie jest połączony");
            return false;
        }
        if (!sid) {
            console.warn("Brak SID — najpierw utwórz linka.");
            return false;
        }
        const paramsMsg = Params.create({ size, speed, color, sid });
        const wsMsg = WebSocketMessage.create({ params: paramsMsg });
        const buffer = WebSocketMessage.encode(wsMsg).finish();
        socket.send(buffer);
        return true;
    };

    const updateParams = () => {
        const ok = sendParams();
        if (!ok) return;
        setIsUpdated(true);
        setTimeout(() => setIsUpdated(false), 1000);
    };

    const createSession = () => {
        if (!socket || socket.readyState !== WebSocket.OPEN) {
            console.warn("WebSocket nie jest połączony");
            return;
        }
        const wsMsg = WebSocketMessage.create({ createSessionRequest: {} });
        const buffer = WebSocketMessage.encode(wsMsg).finish();
        socket.send(buffer);
    };

    // Live update (size + speed) – bez resetu
    const lastSentAtRef = useRef<number>(0);
    const pendingTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
    useEffect(() => {
        if (!sid || !socket || socket.readyState !== WebSocket.OPEN) return;

        const now = Date.now();
        const elapsed = now - lastSentAtRef.current;

        if (elapsed >= THROTTLE_MS) {
            if (sendParams()) lastSentAtRef.current = Date.now();
            return;
        }

        if (pendingTimerRef.current) clearTimeout(pendingTimerRef.current);
        pendingTimerRef.current = setTimeout(() => {
            if (sendParams()) lastSentAtRef.current = Date.now();
            pendingTimerRef.current = null;
        }, THROTTLE_MS - elapsed);

        return () => {
            if (pendingTimerRef.current) {
                clearTimeout(pendingTimerRef.current);
                pendingTimerRef.current = null;
            }
        };
    }, [size, speed, sid]);

    return (
        <div className="host-root">
            <section className="preview-surface">
                <MovingCircle
                    size={size}
                    speed={speed}
                    color={color}
                    boundToParent
                    resetToken={resetToken} // reset tylko na join
                    onBounce={() => setBounceCount(c => c + 1)}
                />
            </section>

            <section className="controls-surface">
                <h2 className="host-title">Host Panel</h2>

                <div className="session-box">
                    <div className="session-row">
                        <div className="left-column">
                            <button type="button" className="create-link-btn" onClick={createSession}>
                                Utwórz linka
                            </button>
                            <div
                                className={`client-status-badge ${clientConnected ? "connected" : "waiting"}`}
                                aria-live="polite"
                            >
                                <span className="dot" />
                                {clientConnected ? "Klient podłączony" : "Oczekiwanie na klienta…"}
                            </div>
                        </div>
                        <div className="bounce-counter">
                            Bounces: <strong>{bounceCount}</strong>
                        </div>
                    </div>

                    {sessionUrl && (
                        <div className="session-url">
                            Link do sesji:&nbsp;
                            <a href={sessionUrl} target="_blank" rel="noreferrer">
                                {sessionUrl}
                            </a>
                        </div>
                    )}
                    {sid && (
                        <div className="session-sid">
                            SID:&nbsp;<code>{sid}</code>
                        </div>
                    )}
                </div>

                <form
                    className="controls-vertical"
                    onSubmit={(e) => {
                        e.preventDefault();
                        updateParams();
                    }}
                >
                    <div className="control">
                        <label htmlFor="size">Size</label>
                        <input
                            id="size"
                            type="range"
                            min={10}
                            max={300}
                            value={size}
                            onChange={(e) => setSize(+e.target.value)}
                        />
                        <div className="value-badge">{size}px</div>
                    </div>

                    <div className="control">
                        <label htmlFor="speed">Speed</label>
                        <input
                            id="speed"
                            type="range"
                            min={50}
                            max={3000}
                            step={10}
                            value={speed}
                            onChange={(e) => setSpeed(+e.target.value)}
                        />
                        <div className="value-badge">{speed}</div>
                    </div>

                    <div className="control">
                        <label htmlFor="color">Color</label>
                        <input
                            id="color"
                            type="color"
                            value={color}
                            onChange={(e) => setColor(e.target.value)}
                        />
                        <div className="value-badge value-badge--mono">{color}</div>
                    </div>

                    <div className="actions">
                        <button
                            type="button"
                            className={`update-btn ${isUpdated ? "clicked" : ""}`}
                            onClick={updateParams}
                            disabled={!sid}
                        >
                            {isUpdated ? "✔ Updated!" : "Update"}
                        </button>
                    </div>
                </form>
            </section>
        </div>
    );
};

export default Host;

// frontend/src/pages/Host.vue
<template>
  <div class="host-root">
    <section class="preview-surface">
      <MovingCircle :size="size" :speed="speed" :color="color" :boundToParent="true" :resetToken="resetToken"
        :shouldStop="!isPlaying" @bounce="bounceCount++" />
    </section>

    <section class="controls-surface">
      <div class="first-row">
        <button type="button" class="btn" @click="onPlayStopPressed">
          {{ isPlaying ? "Stop" : "Play" }}
        </button>

        <div class="bounce-counter">
          Liczba machnięć: <strong>{{ Math.floor(bounceCount / 2) }}</strong>
        </div>

        <div class="control speed-control">
          <label for="speed">Speed</label>
          <input id="speed" type="range" min="50" max="3000" step="10" v-model.number="speed" />
          <div class="value-badge">{{ speed }}</div>
        </div>
      </div>

      <div class="second-row">
        <div class="control">
          <label for="size">Size</label>
          <input id="size" type="range" min="10" max="300" v-model.number="size" />
          <div class="value-badge">{{ size }}px</div>
        </div>

        <div class="control color-control">
          <label for="color">Color</label>
          <input id="color" type="color" v-model="color" />
          <div class="value-badge value-badge--mono">{{ color }}</div>
        </div>
      </div>
      <form class="controls-vertical" @submit.prevent="updateParams">
        <div class="third-row">
          <button type="submit" class="btn" :class="{ clicked: isUpdated }" :disabled="!sid || isUpdated">
            {{ isUpdated ? "✔ Updated!" : "Update" }}
          </button>
          <button type="button" class="btn" @click="createSession">
            Utwórz linka
          </button>
          <div :class="['client-status-badge', clientConnected ? 'connected' : 'waiting']" aria-live="polite">
            <span class="dot"></span>
            {{ clientConnected ? "Klient podłączony" : "Oczekiwanie na klienta…" }}
          </div>
        </div>
      </form>
      <div class="session-box">
        <div v-if="sessionUrl" class="session-url">
          Link do sesji:&nbsp;
          <a :href="sessionUrl" target="_blank" rel="noreferrer">{{ sessionUrl }}</a>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue';
import { WebSocketMessage, Params } from '../proto/messages';
import { socket } from '../socket';
import MovingCircle from '../components/MovingCircle.vue';
import './Host.css';

const THROTTLE_MS = 200;

const savedSize = localStorage.getItem("host-size");
const savedSpeed = localStorage.getItem("host-speed");
const savedColor = localStorage.getItem("host-color");

const size = ref(savedSize ? parseInt(savedSize, 10) : 40);
const speed = ref(savedSpeed ? parseInt(savedSpeed, 10) : 200);
const color = ref(savedColor ? savedColor : "#00ff00");

const isUpdated = ref(false);
const isPlaying = ref(false);

const sessionUrl = ref<string | null>(null);
const sid = ref<string | undefined>(undefined);

const resetToken = ref(0);
const bounceCount = ref(0);
const clientConnected = ref(false);

const toUint8Array = async (data: unknown): Promise<Uint8Array> => {
  if (data instanceof ArrayBuffer) return new Uint8Array(data);
  if (data instanceof Blob) return new Uint8Array(await data.arrayBuffer());
  if (typeof data === "string") return new TextEncoder().encode(data);
  // @ts-ignore
  if (data?.byteLength && data?.buffer) return new Uint8Array(data);
  throw new Error("[Host] Nieznany typ danych z WebSocket");
};

const onMessage = async (ev: MessageEvent) => {
  try {
    const buffer = await toUint8Array(ev.data);
    const msg = WebSocketMessage.decode(buffer);

    if (msg.createSessionResponse) {
      const { accepted, sessionUrl: url } = msg.createSessionResponse;
      if (accepted && url) {
        sessionUrl.value = url;
        clientConnected.value = false;

        try {
          await navigator.clipboard.writeText(url);
          console.log("Copied link to clipboard");
        } catch (err) {
          console.error("Couldn't copy link to clipboard: ", err);
        }

        try {
          const u = new URL(url);
          const s = u.searchParams.get("sid");
          if (s) sid.value = s;
        } catch {
          const parts = String(url).split("sid=");
          if (parts[1]) sid.value = parts[1].split("&")[0];
        }
      }
    } else if (msg.joinSessionResponse) {
      if (msg.joinSessionResponse.accepted) {
        clientConnected.value = true;
        resetToken.value++;
        bounceCount.value = 0;
      }
    }
  } catch (e) {
    console.error("[Host] Decode error:", e);
  }
};

const sendParams = () => {
  if (!socket || socket.readyState !== WebSocket.OPEN) {
    console.warn("WebSocket nie jest połączony");
    return false;
  }
  if (!sid.value) {
    console.warn("Brak SID — najpierw utwórz linka.");
    return false;
  }
  const paramsMsg = Params.create({
    size: size.value,
    speed: speed.value,
    color: color.value,
    sid: sid.value
  });
  const wsMsg = WebSocketMessage.create({ params: paramsMsg });
  const buffer = WebSocketMessage.encode(wsMsg).finish();
  socket.send(buffer);
  return true;
};

const updateParams = () => {
  const ok = sendParams();
  if (!ok) return;
  isUpdated.value = true;
  setTimeout(() => isUpdated.value = false, 1000);
};

const createSession = () => {
  if (!socket || socket.readyState !== WebSocket.OPEN) {
    console.warn("WebSocket nie jest połączony");
    return;
  }
  const wsMsg = WebSocketMessage.create({ createSessionRequest: {} });
  const buffer = WebSocketMessage.encode(wsMsg).finish();
  socket.send(buffer);
};

const onPlayStopPressed = () => {
  if (!socket || socket.readyState !== WebSocket.OPEN) {
    console.warn("WebSocket nie jest połączony");
  } else {
    let wsMsg: WebSocketMessage;
    if (!isPlaying.value) {
      wsMsg = WebSocketMessage.create({ play: {} });
    } else {
      wsMsg = WebSocketMessage.create({ stop: {} });
    }
    const buffer = WebSocketMessage.encode(wsMsg).finish();
    socket.send(buffer);
  }
  isPlaying.value = !isPlaying.value;
  bounceCount.value = 0;
};

onMounted(() => {
  if (socket) socket.binaryType = "arraybuffer";
  socket.addEventListener("message", onMessage);
});

onUnmounted(() => {
  socket.removeEventListener("message", onMessage);
});

let lastSentAt = 0;
let pendingTimer: ReturnType<typeof setTimeout> | null = null;

watch([size, speed, sid], () => {
  if (!sid.value || !socket || socket.readyState !== WebSocket.OPEN) return;

  const now = Date.now();
  const elapsed = now - lastSentAt;

  if (elapsed >= THROTTLE_MS) {
    if (sendParams()) lastSentAt = Date.now();
    return;
  }

  if (pendingTimer) clearTimeout(pendingTimer);
  pendingTimer = setTimeout(() => {
    if (sendParams()) lastSentAt = Date.now();
    pendingTimer = null;
  }, THROTTLE_MS - elapsed);
});

watch([size, speed, color], ([newSize, newSpeed, newColor]) => {
  localStorage.setItem("host-size", newSize.toString());
  localStorage.setItem("host-speed", newSpeed.toString());
  localStorage.setItem("host-color", newColor);
});
</script>
